# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'messagingFirestoreVn' do
  
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFirebaseStarter

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.3.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob'
  pod 'Firebase/Auth' , '~> 5.3.0'
  # pod 'Firebase/Database'
  # pod 'Firebase/DynamicLinks'
  # pod 'Firebase/Performance'
  # pod 'Firebase/Firestore'
  # pod 'Firebase/Messaging'
  # pod 'Firebase/RemoteConfig'
  # pod 'Firebase/Storage'
  
  # pod 'Fabric', '~> 1.7.6'
  # pod 'Crashlytics', '~> 3.10.1'

  # source 'https://github.com/CocoaPods/Specs.git'
end
